resources:
  - ../../base
  - namespace.yaml

patchesJson6902:
  - target:
      group: ""
      version: v1
      kind: ConfigMap
      name: dynamic-config
    path: url-patch.json

namespace: cuid01

