apiVersion: v1
kind: ConfigMap
metadata:
  name: dynamic-config
data:
  dynamic.yml: |
    http:
      services:
        proxmox:
          loadBalancer:
            servers:
              - url: https://192.168.1.101

