apiVersion: v1
kind: ConfigMap
metadata:
  name: dynamic-config
data:
  dynamic.yml: |
    http:
      routers:
        proxmox-router:
          rule: "Host(`192.168.1.143`)"
          service: proxmox
          entryPoints:
            - websecure
          tls: {}
      services:
        proxmox:
          loadBalancer:
            servers:
              - url: "https://192.168.1.101:8006"
            passHostHeader: true

