apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
  namespace: traefik-tools
data:
  dynamic.yaml: |
    http:
      routers:
        proxmox-router:
          rule: "PathPrefix(`/`)"
          service: proxmox-service
          entryPoints:
            - websecure

        dashboard-router:
          rule: "PathPrefix(`/dashboard`)"
          service: api@internal
          entryPoints:
            - traefik

      services:
        proxmox-service:
          loadBalancer:
            servers:
            - url: "https://192.168.1.101:8006"

