apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
data:
  traefik.yml: |
    entryPoints:
      web:
        address: ":80"
      websecure:
        address: ":443"
      dashboard:
        address: ":8081"
    api:
      dashboard: true
      insecure: true
    providers:
      file:
        filename: "/config/dynamic.yml"
    log:
      level: DEBUG
    serversTransport:
      insecureSkipVerify: true

