apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: traefik-tools
spec:
  selector:
    app: traefik
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080
  - protocol: TCP
    port: 443
    targetPort: 443
    nodePort: 30081

