apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik
  namespace: traefik-tools
  labels:
    app: traefik
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      containers:
      - name: traefik
        image: traefik:v2.10
        args:
        - "--entrypoints.web.address=:80"
        - "--entrypoints.websecure.address=:443"
        - --entrypoints.traefik.address=:8080
        - "--providers.file.filename=/etc/traefik/dynamic.yaml"
        - "--log.level=DEBUG"
        - "--accesslog=true"
        - "--api.insecure=true"
        - "--api.dashboard=true"
        - "--serversTransport.insecureSkipVerify=true"
        ports:
        - name: web
          containerPort: 80
        - name: websecure
          containerPort: 443
        - name: traefik
          containerPort: 8080
        volumeMounts:
        - name: traefik-config
          mountPath: /etc/traefik/dynamic.yaml
          subPath: dynamic.yaml
      volumes:
      - name: traefik-config
        configMap:
          name: traefik-config

