apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: traefik-tools
spec:
  selector:
    app: traefik
  type: NodePort
  ports:
    - protocol: TCP
      name: web
      port: 80         # Internal port (entryPoint: web)
      targetPort: 80   # Container port
      nodePort: 30080  # Exposed NodePort
    - protocol: TCP
      name: websecure
      port: 443        # Internal port (entryPoint: websecure)
      targetPort: 443  # Container port
      nodePort: 30081  # Exposed NodePort
