apiVersion: v1
kind: ConfigMap
metadata:
  name: dynamic-config
  namespace: {{ .Values.namespace }}
data:
  dynamic.yml: |
    http:
      routers:
        proxmox-router:
          rule: "PathPrefix(`/`)"
          service: proxmox
          entryPoints:
            - websecure
          tls: {}
      services:
        proxmox:
          loadBalancer:
            servers:
              - url: {{ .Values.proxmox.url }}
            passHostHeader: true

