apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
  namespace: {{ .Values.namespace }}
data:
  traefik.yml: |
    entryPoints:
      web:
        address: ":80"
      websecure:
        address: ":443"
    api:
      dashboard: true
    providers:
      file:
        filename: "/config"
        watch: true
    log:
      level: DEBUG
    serversTransport:
      insecureSkipVerify: true

