apiVersion: v1
kind: ConfigMap
metadata:
  name: dynamic-config
data:
  dynamic.yml: |
    http:
      routers:
        proxmox-router:
          rule: "PathPrefix(`/`)"
          service: proxmox
          entryPoints:
            - websecure
          tls: {}
      services:
        proxmox:
          loadBalancer:
            servers:
              - url: https://1.1.1.1
            passHostHeader: true

