apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik
  labels:
    app: traefik
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      containers:
      - name: traefik
        image: traefik:v2.10
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        - name: dashboard
          containerPort: 8081
        volumeMounts:
        - name: traefik-config
          mountPath: /etc/traefik/traefik.yml
          subPath: traefik.yml
        - name: dynamic-config
          mountPath: /config/dynamic.yml
          subPath: dynamic.yml
        - name: docker-socket
          mountPath: /var/run/docker.sock
      volumes:
      - name: traefik-config
        configMap:
          name: traefik-config
      - name: dynamic-config
        configMap:
          name: dynamic-config
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock

