apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
data:
  traefik.yml: |
    entryPoints:
      web:
        address: ":80"
      websecure:
        address: ":443"

    api:
      dashboard: true
    providers:
      file:
        filename: "/config/dynamic.yml"
        watch: true
    log:
      level: DEBUG
    serversTransport:
      insecureSkipVerify: true

