apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-world-config
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Hello, World!2</title>
    </head>
    <body>
      <h1>Hello, World!</h1>
    </body>
    </html>
