apiVersion: apps/v1
kind: Deployment
metadata:
  name: envoy-proxy
  namespace: proxmox-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: envoy-proxy
  template:
    metadata:
      labels:
        app: envoy-proxy
    spec:
      containers:
      - name: envoy
        image: envoyproxy/envoy:v1.24.0
        args:
          - "-c"
          - "/etc/envoy/envoy.yaml"
        volumeMounts:
        - name: envoy-config
          mountPath: /etc/envoy
        ports:
        - containerPort: 443  # HTTPS traffic
      volumes:
      - name: envoy-config
        configMap:
          name: envoy-config

