apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-config
  namespace: proxmox-proxy
data:
  haproxy.cfg: |
    global
        log stdout format raw local0
        maxconn 4096

    defaults
        log global
        mode tcp
        option tcplog
        timeout connect 10s
        timeout client  30s
        timeout server  30s

    frontend https_proxy
        bind *:443
        default_backend proxmox_backend

    backend proxmox_backend
        server proxmox 192.168.1.101:8006 check ssl verify none

