apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
  namespace: debug-tools  # Replace with the desired namespace
  labels:
    app: debug-pod
spec:
  containers:
  - name: debug-container
    image: ubuntu:20.04  # Use an image with a package manager like apt
    command: [ "sleep", "infinity" ]  # Keep the pod running indefinitely
    stdin: true
    tty: true
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "256Mi"
    securityContext:
      allowPrivilegeEscalation: true
      capabilities:
        add:
        - NET_ADMIN
  restartPolicy: Always

