apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
  namespace: debug-tools  # Ensure this namespace is created in advance or managed by ArgoCD
  labels:
    app: debug-pod
spec:
  containers:
  - name: debug-container
    image: ubuntu:20.04  # A lightweight image with apt support
    command: [ "sleep", "infinity" ]  # Keep the pod running
    stdin: true
    tty: true
    securityContext:
      allowPrivilegeEscalation: true  # Allow for advanced networking tools like `ping`
      capabilities:
        add:
        - NET_ADMIN  # Required for certain networking commands
        - SYS_ADMIN
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "256Mi"
  restartPolicy: Always

